POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Antonella Summit33",
    "details": "Feira gastronomica",
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/2985bbb6-e92b-4ccf-b828-610ecbbe667a/attendees
Content-Type: application/json

{
    "name": "Luiz Sanchez",
    "email": "luizcsanchezzf0@gmail.com"
} 

###

GET http://localhost:3333/events/7b0691b8-9697-4da5-87a5-9e2a4a3792ca

